spring: 
  profiles:
    active: 
      - dev
---
server:
  post: 8201
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7002/eureka/
demo:
  hello: 12345
---
server:
  post: 8202
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/
